steps: 
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-west1-docker.pkg.dev/emergya-digital-cloud-lab/test/testimage', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-west1-docker.pkg.dev/emergya-digital-cloud-lab/test/testimage']
